#!/usr/bin/env bash

cd `dirname $0`

NEO4J_VERSION="neo4j-community-2.1.2"

NEORAM_HOME=`pwd`
OPT=$NEORAM_HOME/opt
VAR=$NEORAM_HOME/var
RAMDISK=$NEORAM_HOME/ramdisk

NEO4J_HOME=$OPT/neo4j

function download {
    # $1 - NEO4J_VERSION
    echo "Downloading $1..."
    mkdir -p $OPT 2> /dev/null
    cd $OPT
    curl -f -o $1-unix.tar.gz http://dist.neo4j.org/$1-unix.tar.gz
    STATUS=$?
    if [ $STATUS != 0 ]
    then
        exit $STATUS
    fi
    tar zxf $1-unix.tar.gz
    #ln -s $1 neo4j
    echo ""
}

function ensure_downloaded {
    # $1 - NEO4J_VERSION
    if [ ! -e $OPT/$1 ]
    then
        download $1
    fi
}

function use {
    # $1 - NEO4J_VERSION
    ensure_downloaded $1
    cd $OPT
    rm neo4j
    ln -s $1 neo4j
}

function start {
    use $NEO4J_VERSION
    rm -rf $NEO4J_HOME/data/graph.db
    if [ "$1" == "" ]
    then
        echo "Creating new database"
        mkdir $RAMDISK/graph.db
    else
        LOAD_FROM=$1
        echo "Loading database '$LOAD_FROM'"
        mkdir -p $VAR 2> /dev/null
        cp -a $VAR/$LOAD_FROM $RAMDISK/graph.db
    fi
    ln -s ../../../ramdisk/graph.db $NEO4J_HOME/data/graph.db
    $NEO4J_HOME/bin/neo4j start
    echo ""
}

function stop {
    $NEO4J_HOME/bin/neo4j stop
    rm -rf $NEO4J_HOME/data/graph.db
    if [ "$1" == "" ]
    then
        echo "Dropping database"
        rm -rf $RAMDISK/*
    else
        SAVE_TO=$1
        echo "Saving database '$SAVE_TO'"
        mkdir -p $VAR 2> /dev/null
        mv $RAMDISK/graph.db $VAR/$SAVE_TO
    fi
    echo ""
}

function usage {
    echo "$0 start [<load_from>]"
    echo "$0 stop [<save_to>]"
}


COMMAND=$1
shift

case "$COMMAND" in
download)
    download
    ;;
start)
    start $*
    ;;
stop)
    stop $*
    ;;
use)
    use "neo4j-community-$1"
    ;;
*)
    usage
esac

